execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"              50"}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":" 50 "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"      50"}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"     "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"              50"}]}