execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"                   1000"}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":" 1000 "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"                   1000"}]}