execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"                   2500"}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"         "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":" 2500  2500"}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"        "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"         "}]}
execute @e[type=npc] ^^^ execute @a ^^^ tellraw @s {"rawtext":[{"text":"                   2500"}]}