gamemode s @a
execute @a ^^^ tp @a[tag=team1] @r[tag=team1]
execute @a ^^^ tp @a[tag=team2] @r[tag=team2]
execute @a ^^^ tp @a[tag=team3] @r[tag=team3]
execute @a ^^^ tp @a[tag=team4] @r[tag=team4]
execute @a ^^^ tp @a[tag=team5] @r[tag=team5]
execute @a ^^^ tp @a[tag=team6] @r[tag=team6]
execute @a ^^^ tp @a[tag=team7] @r[tag=team7]
execute @a ^^^ tp @a[tag=team8] @r[tag=team8]
execute @a ^^^ tp @a[tag=team9] @r[tag=team9]
execute @a ^^^ tp @a[tag=team10] @r[tag=team10]
execute @a ^^^ tp @a[tag=team11] @r[tag=team11]
execute @a ^^^ tp @a[tag=team12] @r[tag=team12]
execute @a ^^^ tp @a[tag=team13] @r[tag=team13]